title: Võ Tiến Phát Blog
description: Blog chia sẻ kiến thức Java & JavaScript
author: Võ Tiến Phát

baseurl: "/Portfolio"
url: "https://tien-phatt.github.io"

markdown: kramdown
theme: null

permalink: /blog/:title/
